name: Release
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Start Web Release Build
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
        run: flutter build web --release --no-web-resources-cdn --web-renderer html

      - name: Upload to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web

      - name: Deploy to pages
        uses: actions/deploy-pages@v4

      - name: Start Android Release Build
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
        run: flutter build apk --release

      - name: Publish build
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.sha }}
          name: ${{ github.sha }}
          body: |
            This is a automatic build of the `main` branch.
          artifacts: 'build/app/outputs/flutter-apk/*.apk'
          allowUpdates: true
          prerelease: false
